# Generated by Django 5.0.3 on 2024-03-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
    ]
